/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KycSystem } from "./KycSystem";
export * as factories from "./factories";
export { KycSystem__factory } from "./factories/KycSystem__factory";
